### ISSUE TITLE
兄弟你博客挂了

### ISSUE THREAD

**Issue by changyexing** [moeik/Heroku_aria2#11]
老哥那几个命令是啥啊。我忘了。。。想重新申请token，你博客挂了

**Comment by moeik** [comment]
抱歉，没想到还有人在访问 正在更换web服务器 请稍等

**Comment by changyexing** [comment]
不要紧。。。我在网页快照网站找到记录了，重新找token还是不行。。。这个项目还能使用吗？可以下载不能上传，附上截图
![image](https://user-images.githubusercontent.com/47708150/122642678-3f977480-d13e-11eb-9791-1e88167c1bf8.png)
求帮忙看看😢
